export const COIN_IDS = [
  "bitcoin",
  "ethereum",
  "binancecoin",
  "solana",
  "ripple",
  "cardano",
  "dogecoin",
  "litecoin",
  "bitcoin-cash",
  "polkadot",
  "dash",
  "zcash",
  "qtum",
];

export const COIN_ICONS: Record<string, string> = {
  bitcoin: "₿",
  ethereum: "Ξ",
  binancecoin: "BNB",
  solana: "◎",
  xrp: "✕",
  cardano: "₳",
  dogecoin: "Ð",
  litecoin: "Ł",
  "bitcoin-cash": "₿",
  polkadot: "●",
  dash: "◆",
  zcash: "ⓩ",
  qtum: "◈",
};

export const COIN_COLORS: Record<string, string> = {
  bitcoin: "#F7931A",
  ethereum: "#627EEA",
  binancecoin: "#F0B90B",
  solana: "#00FFA3",
  xrp: "#23292F",
  cardano: "#0033AD",
  dogecoin: "#C3A634",
  litecoin: "#A6A6A6",
  "bitcoin-cash": "#4CC947",
  polkadot: "#E6007A",
  dash: "#008CE7",
  zcash: "#ECB244",
  qtum: "#2E9AD0",
};
